version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
